### ISSUE TITLE
UnvScript is not a descriptive name

### ISSUE THREAD

**Issue by Pandademic** [UnvLabs/Web#2]
Unv-to-JS could be better?

**Comment by ksenginew** [comment]
**Unv.JS**??

**Comment by ksenginew** [comment]
This repo is for web platform of Unv. So I thought to rename this to _web_. Any thoughts?

**Comment by Pandademic** [comment]
I think _web_ is the best so far

**Comment by ksenginew** [comment]
I am writing  a production level Unv compiler for web. It's very hard. Share some learning resources or ideas with me if you can.

**Comment by Pandademic** [comment]
Got it , maybe: https://craftinginterpreters.com/

**Comment by ksenginew** [comment]
Closing issue because name is resolved
